### ISSUE TITLE
修改系统默认的镜像源

### ISSUE THREAD

**Issue by lichunqiang** [jason-chang/centstead#1]
把默认的镜像源修改成163等国内比较快的怎么样

**Comment by jason-chang** [comment]
如果是 centos epel 源,  默认是支持国内镜像的，
Mysql community 版本默认使用的时 oracle 官方镜像，我这里速度能达到 1M
MariaDB 使用的是 Aliyun 的镜像
PostgreSQL 默认使用官方镜像 同样 下载速度能达到1M 

其他:
如果你发现 安装中 经常卡在加载数据源上，可能是 nodejs 源造成的，
如果平时不更新 nodejs 版本 可以编辑 node-resorce.repo 禁用 nodejs 源

稍等晚上打包的版本还会添加 Laravel 队列监听功能, 
还有之前的版本 基础盒子, 有一个 Bug supervisor 没有成功安装，
如果用 supervisor 的话，晚上更新下 基础盒子吧。 见 百度网盘   `2016-06-15` 文件夹。

打包好了,会再恢复通知你下的

**Comment by lichunqiang** [comment]
果然是nodejs那个搞得慢死了

**Comment by jason-chang** [comment]
OK更新推送了, 可以 git pull 拉取变更，也可以下载 [Latest release](https://github.com/jason-chang/centstead/releases/latest) .
现在默认禁用了 nodejs 源, 
更新 nodejs 可以通过 `yum install -y nodejs  --enablerepo=nodesource` 启用 nodesource源

**Comment by lichunqiang** [comment]
:+1:

**Comment by klgd** [comment]
mysql 的源怎么换？我这边只有20k/s的速度，还老是安装出错

**Comment by jason-chang** [comment]
mysql 默认使用 官方源
