### ISSUE TITLE
用离线下载的方式 vagrant up会重新下载box

### ISSUE THREAD

**Issue by snowboy8** [jason-chang/centstead#2]
HI，使用下面的方式添加的box 好像因为没有version导致vagrant up 启动时会重新下载box
vagrant box add ./avant.box --name=jason-chang/centstead-avant

**Comment by jason-chang** [comment]
奥， 你本地先在本地注释 行
#config.vm.box_version = settings["version"] ||= ">= 1.1.1"

稍等我Commit下，去掉版本检测。

**Comment by jason-chang** [comment]
另外，麻烦你试下你那里官方源的速度给反馈下吧，
我这里下载能达到1-3M，只是上传得挂代理。

**Comment by jason-chang** [comment]
不用注释 Centstead.rb 了, 请在 config/config.yml，`box:` 行后添加一行

version: ">=0"

即可

**Comment by snowboy8** [comment]
下载速度惨不忍睹，平均是10kb以下

**Comment by snowboy8** [comment]
另外能介绍一下config.yml在windows下的配置吗，在这块遇到了一些问题

**Comment by jason-chang** [comment]
一些问题？请具体描述下，我的开发环境既是windows。

**Comment by snowboy8** [comment]
![360 20160620203759](https://cloud.githubusercontent.com/assets/13285413/16194396/f749face-3726-11e6-85f4-d58dbc07418d.jpg)
我现在启动vagrant up出现这样的错误，应该是config.yml没有配置对

**Comment by jason-chang** [comment]
这里在启动之前需要自行配置，从文本可以看出，那是示例配置 比如这样
![image](https://cloud.githubusercontent.com/assets/4367687/16194582/d997b9ca-3727-11e6-9c96-963f233118b3.png)

**Comment by snowboy8** [comment]
![360 20160620204935](https://cloud.githubusercontent.com/assets/13285413/16194707/8a626afc-3728-11e6-8501-2f578d1c96f5.jpg)
这块不需要配置吗

**Comment by jason-chang** [comment]
如果你不需要 拷贝文件的话， 请注释掉

**Comment by jason-chang** [comment]
建议尽量使用 共享文件夹同步文件 到虚拟机

**Comment by snowboy8** [comment]
![3](https://cloud.githubusercontent.com/assets/13285413/16194826/2f50421e-3729-11e6-9673-14c377f295c7.jpg)
现在启动了，提示这样的错误

**Comment by jason-chang** [comment]
没有问题，虚拟机启动过程，vagrant 无法判断虚拟机是否完全启动，所以会多次尝试连接。

**Comment by snowboy8** [comment]
![6](https://cloud.githubusercontent.com/assets/13285413/16194907/b2449fda-3729-11e6-910f-697bcd8d33a2.jpg)
等了几分钟现在一直提示认证失败

**Comment by snowboy8** [comment]
![7](https://cloud.githubusercontent.com/assets/13285413/16194944/d6a200e8-3729-11e6-92fc-e8f7d202c6bb.jpg)

最终提示启动超时了

**Comment by jason-chang** [comment]
你的 vagrant 版本，与 virtualBox 版本是？
请 vagrant destroy -f 销毁后 vagrant up 重启试试。

**Comment by snowboy8** [comment]
![image](https://cloud.githubusercontent.com/assets/13285413/16195241/3f1ff9c6-372b-11e6-817f-cc18a4782e9b.png)
后来在vagrantfile里面增加了这些配置就启动成功了
![image](https://cloud.githubusercontent.com/assets/13285413/16195286/6f7b6b96-372b-11e6-8216-06d755abb187.png)
应该是这里没有配置正确吧，这块你那是怎么配置的哦

**Comment by jason-chang** [comment]
你这些配置是跳过 linux 的公私钥认证,  使用 账户密码登录, 官方不推荐
 配置文件里的`authorize` 和 `keys` 算是一种福利, 方便用户与虚拟环境建立 公私钥认证.
vagrant本身与虚拟机通信和这两项无关.

你报下你的 `vagrant -v` 版本吧，还有 virtualbox 是 5.0 + 吗？

![image](https://cloud.githubusercontent.com/assets/4367687/16195665/423f2bac-372d-11e6-9f08-ad1e866df532.png)

**Comment by snowboy8** [comment]
![image](https://cloud.githubusercontent.com/assets/13285413/16196097/1a8c2662-372f-11e6-967d-f52aa8fc46c5.png)
![image](https://cloud.githubusercontent.com/assets/13285413/16196108/28bbbd06-372f-11e6-9b2b-8ac403b7b52b.png)

**Comment by snowboy8** [comment]
![image](https://cloud.githubusercontent.com/assets/13285413/16197002/e03d32ae-3732-11e6-9cd1-ca8287930406.png)
恢复之后又是这样的错误了

**Comment by jason-chang** [comment]
恩，对 目前暂时找不到问题了.
我试试重装 vagrant , virtualbox , 看是否重现你的问题, 
你就先改 vagrantfile 使用吧, 其他方面还有问题, 请再反馈
